---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels: 
    app.kubernetes.io/instance: chat-demo-test
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: chat-demo-test 
  name: chat-demo-test
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi