apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: chat-demo-test
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: chat-demo-test 
  name: chat-demo-test
spec:
  ports:
  - port: 8501
    protocol: TCP
    targetPort: 8501
  selector:
    app.kubernetes.io/instance: chat-demo-test 
